# офіційний Python образ
FROM python:3.10-slim

# залежності
WORKDIR /app
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# копіюємо код застосунку
COPY . .

# відкриваємо порт FastAPI
EXPOSE 8000

# запускаємо застосунок
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
